apiVersion: v1
kind: Service
metadata:
  name: kms
  labels:
    app: kms
  annotations:
    ves.io/virtual-sites: kurentotest/vsite1
spec:
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: kms-port
  selector:
    app: kms
  type: ClusterIP
