apiVersion: v1
kind: Service
metadata:
  name: kurent-platedetector
  labels:
    app: kurent-platedetector
  annotations:
    ves.io/virtual-sites: kurentotest/vsite1
spec:
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: kurent-platedetector
  selector:
    app: kurent-platedetector
  type: ClusterIP
